name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  APP_ENV: testing
  APP_DEBUG: "false"
  APP_KEY: ThisIsARandomStringForTests12345
  APP_TIMEZONE: UTC
  APP_URL: http://localhost/
  CACHE_DRIVER: array
  MAIL_MAILER: array
  SESSION_DRIVER: array
  QUEUE_CONNECTION: sync
  GUZZLE_TIMEOUT: 60
  GUZZLE_CONNECT_TIMEOUT: 60

jobs:
  postgresql:
    name: PostgreSQL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.5]
        database: ["postgres:18"]
        include:
          - database: "postgres:18"
            tmpfs: /var/lib/postgresql
    services:
      database:
        image: ${{ matrix.database }}
        env:
          POSTGRES_DB: testing
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --tmpfs ${{ matrix.tmpfs }}:rw
          --health-cmd pg_isready
          --health-interval 2s
          --health-timeout 5s
          --health-retries 30
    env:
      DB_CONNECTION: pgsql
      DB_HOST: 127.0.0.1
      DB_DATABASE: testing
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6

      - name: Get cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.php }}-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: bcmath, curl, gd, mbstring, mysql, openssl, pdo, tokenizer, xml, zip
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-suggest --no-progress --no-scripts

      - name: Run Migrations
        run: php artisan migrate --force --seed

      - name: Integration tests
        run: vendor/bin/pest tests/Integration --parallel --do-not-fail-on-phpunit-warning